package com.moomark.post.exception

private const val ERROR_BASE_CODE = 100000
private const val CANNOT_FIND_POST_OFFSET = 1
private const val CANNOT_FIND_CATEGORY_OFFSET = 2
private const val CANNOT_FIND_PARENT_CATEGORY_OFFSET = 3
private const val CANNOT_FIND_CHILD_CATEGORY_OFFSET = 4

enum class ErrorCode(
    val msg: String,
    val code: Int,
) {
    DONT_KNOW_ERROR("DOESN'T KNOW ERROR", ERROR_BASE_CODE),
    CANNOT_FIND_POST("CANNOT_FIND_POSTINFO", ERROR_BASE_CODE + CANNOT_FIND_POST_OFFSET),
    CANNOT_FIND_CATEGORY("CANNOT_FIND_CATEGORYINFO", ERROR_BASE_CODE + CANNOT_FIND_CATEGORY_OFFSET),
    CANNOT_FIND_PARENT_CATEGORY("CANNOT_FIND_PARENT_CATEGORY", ERROR_BASE_CODE + CANNOT_FIND_PARENT_CATEGORY_OFFSET),
    CANNOT_FIND_CHILD_CATEGORY("CANNOT_FIND_CHILD_CATEGORY", ERROR_BASE_CODE + CANNOT_FIND_CHILD_CATEGORY_OFFSET),
}
