name: github-actions/gradle/checkstyle
on:
  pull_request:
    branches:
      - develop

  push:
    branches:
      - develop

jobs:
  lint:
    name: Checkstyle
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Run all check
        run: ./gradlew check -x compileJava -x checkstyleTest -x compileTestJava --stacktrace

      - name: Update artifact
        uses: actions/upload-artifact@v4
        if: ${{ failure() }}
        with:
          name: auth-result
          path: build/reports
